[package]
name = "pdas"
version = "0.1.0"
authors = ["Gregor Reitzenstein <me@dequbed.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
config = { version = "0.9", features = ["toml"] }

slog = "2.5"
slog-term = "2.5"
slog-async = "2.5"

rarian = { path = "../../lib/rarian" }
git-annex = { path = "../../lib/annex" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

dirs = "2.0"

[dev-dependencies]
maplit = "1.0"
