[package]
name = "pdas"
version = "0.1.0"
authors = ["Gregor Reitzenstein <me@dequbed.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
directories = "2.0"
log = "0.4"
stderrlog = "0.4"

rarian = { path = "../../lib/rarian" }
git-annex = { path = "../../lib/annex" }

[dev-dependencies]
maplit = "1.0"
